dist: trusty
sudo: required
language: java
jdk:
- openjdk11
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: wcBlPov1dHaoXhioAfmtL/xz1SCKJYtUNbMbyFFLi8Tjf6o4wuMYAhB6Q+1mEVfBMpz5NsjSmvdb6YnieWAcI9MOke3OrVfKCWs4NVG3mpHBpIjTHY5EMHKGC8R6u8B1zph5YyebZE60uDs7He7aw9zBuQrAaNXJTZu5l5cG33agD6LJTQnqPjxXkv8rvqac7PHSd6N58euf2e4yakKf2247RNqvYfQymfnsU6YMmpV0qHobt2RwSxxTY7FZDRWuJvcnO0+5Z4lqVDV7qwHJNvw0F39YWVAm9zzaSG806+NI+tnSeD05wf0sB8Ndj8smp2W10R8HRoQXoT+H0usjpwWqnavn0mqpg7tW8BIA5GilOIFIQrtaF2ykBmt51qvhwxhBVGCShcOlf7DzfguTdRL77pYV6R/8KzCiN08cQ9BCR9n4K4usizuClRgpKVow+oqyQUs49wsEZyuLZuCdsHFyqLrKQFBEO02LNLETMvi/fmi4lf6qMp0GpICKvFzIs7+S2dt//kUjzo+2TvvkaF44vXgQrC/VaY2Qx8I07O0TLfYcrw5blkIMulQubvzYQ7RsjNvA+Z5LLryawkR9x1xOTB56tXasjuzdsDfn8gefzSbhjmMcioHZphY0bMB1k3v0p6jAu8ZQrvtKomxsJzRxVAwLsY+hAqCgF3u/VQM=
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2,TLSv1,TLSv1.1
    - secure: oa/Udj7NKC3MgM0JeQ0rp12Pt8Y/ArhNczJXBWqK9t/unIA9LToAbzox1mxMGcX8g1v9rdg1dMUdUnJqrI45ayBy8BRY5AnYB7hQ8Q0uWov/25UpQ3iy+hTr2Xx/uRLplHAOhtz16sUv3LX8INoR0yQEzFOBgbTAb9tE47vqy69PgfAd4igXt+NaGia6DG8SEf3BP+kXuYxfro7Aem6LNGIIrtVL7hhbDsyA48t0+bFAlODmRL38m+JaTWUbN15FLeclGHjBFdg8KHZFrBI52h40fKuuEtOZ30v4nRAaZTGUqJ5fVfUyyuQoABzsvjLO9QMgILgPZDCjKUu30lZJqtWyhpD9VejiozYBCmIr4gonS90tx8qW8IEeGyxF9I7wLiRNaCWtz463broU5aYQ7Yxa5SRv0+QJS/9O8G1bevAZc5Tq0qMhYMUaa3diqI95UK/DiHqkM/QFU+HSaK0R2WDDjtLxebFL5kjVjAVma+wponk+b8YFJ59IzvgQ+cMRdxgJZiQJdhZbFdIiQcRtE+PNhOzl9mlmUxMXgl+xUsPZTqXYo4aAlryjVhZk4LDLg0l6MzsfpkbgZc6Hw2A5N/V98C9ywn2y7Gfxu75zMpMsE51LET4qyvg/qH451iDGB2PEYw8YBoniDwR/w1U1yCP2Y4gTWji+iwEpLGG3t+g=
